### ISSUE TITLE
[Bug]: PDFs können nicht geöffnet/angezeigt werden

### ISSUE THREAD

**Issue by BillyTheKing** [lotta-schule/core#14]
### Bug-Beschreibung

**Was ist passiert:**
Mehrere Nutzer melden, dass beim Klick auf eine PDF, selbige nicht angezeigt bzw. runtergeladen wird, sondern ein Quellcode angezeigt wird.

Der Fehler konnte nachgestellt werden, bspw: https://info.lotta.schule/a/1240-2022
Der Fehler bezieht sich nicht nur auf PDFs sondern auf alle Dateitypen, die über das **Download-Modul**, zum Herunterladen verfügbar sind.

Die Fehlermeldung/Der angezeigte Quellcode:
```
<Error>
<Code>InvalidRequest</Code>
<Message>
Request specific response headers cannot be used for anonymous GET requests.
</Message>
<Resource>
/AAA/BBB/CCCCDDDDEEEEFFFF(geändert)
</Resource>
<RequestId>txgf57909492b484cc493cc-0065b4cb57</RequestId>
</Error>
```

**Ursache**: keine Vermutung, die Konsole zeigt keine Fehlermeldung an

### Link zur Seite, auf der das Problem aufgefallen ist

https://info.lotta.schule/a/1240-2022

### Gerätekategorie

Trifft hier nicht zu

### In welchem Browser ist das Problem aufgetreten

Firefox

**Comment by techotline** [comment]
@BillyTheKing der Bug ist leider nicht vom Browser abhängig, da er derzeit auch (noch) in Safari auftritt.

**Comment by BillyTheKing** [comment]
@techotline sagt auch keiner. Ich habe nur gemeldet, in welchem Browser ich den Fehler nachgestellt habe.

**Comment by techotline** [comment]
> @techotline sagt auch keiner. Ich habe nur gemeldet, in welchem Browser ich den Fehler nachgestellt habe.

OK, Beschreibung ist nachvollziehbar! Wir haben das vermutlich beide missverstanden. Daher mein Hinweis: Bug tritt auch in Safari auf. LG

**Comment by ptitmouton** [comment]
OK das ist ein interessantes "Problem" dass durch den Wegzug der Daten von ionos entstanden ist.

[TLDR] Die nächsten paar Absätze bis zu den Sprechblasen erklären das Problem und sind für die Lösung nicht besonders relevant wenn auch durchaus interessant.

Das Download-Modul lässt sich von unserem Backend eine URL für die Datei geben die mit dem Parameter `?response-content-disposition` den Server dazu bringt den [Content-Disposition Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) zu setzen, so dass der Browser die Datei heruntergeladen hat, wozu er sich auch nur recht schwer drängen lässt wenn die Datei nicht vom selben Host ausgeliefert wird wie die Seite.

Das hat bei dem S3-kompatiblen Storage von IONOS auch immer wunderbar geklappt, auch mit der öffentlichen URL, scaleway lehnt hier die Anfrage ab wie in dem Beispiel ja klar beschrieben ist mit der Aussage

> Request specific response headers cannot be used for anonymous GET requests.

Also dass diese nachträglichen Einstellungen über die URL nur bei authentifizierten Anfragen erlaubt sind, nicht bei öffentlichen.

Ich habe mal geschaut und [Amazon dokumentiert die Funktion für S3](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html) recht gut, wobei explizit auch erwähnt wird dass es authentifizierte Anfragen sein müssen.
<img width="80%" alt="Screenshot 2024-01-27 at 23 06 11" src="https://github.com/lotta-schule/web/assets/1842883/330793ab-ba7e-49fb-bf8f-0e5aacc1be7d">

Genau genommen hätte es also eigentlich auch schon vorher nicht funktionieren dürfen und die Tatsache, dass unser neuer Anbieter sich an die Spezifikation hält bringt uns hier Probleme...

💭🗯️💬

Wir haben hier mittelfristig ein paar Möglichkeiten, wie wir den Download zurückbringen. Die Dateiverwaltung ist eigentlich die nächste große Baustelle wenn wir endlich mal die Bugs, um die sich die letzten Jahre keiner gekümmert hat, schneller abarbeiten können als sie @techotline melden kann 😅

Bis dahin kann ich erstmal ein Hotfix für [lotta-schule/core](https://github.com/lotta-schule/core) fertig machen, der die Unterstützung für den Parameter `?request-content-disposition` entfernt. Vermutlich wird das Downloadmodul (und andere Stellen wo wir bisher ein Download erzwungen haben) dann in den meisten Browsern Dateien öffnen statt sie herunterzuladen wenn er sie für anzeigbar hält, hier wird aber "Rechtsklick > Speichern unter" noch eine Weile reichen müssen. Kurzfristig ist da auf jeden Fall nichts zu machen.

**Comment by techotline** [comment]
@ptitmouton verstehe Deine Erläuterungen. Jedoch eine Anmerkung bzw. Frage: in der mobil-view von iOS setzt Apple primär darauf, Dateien anzuzeigen und zwischen zwei Optionen (optional) zwei Buttons zu wählen: Anzeigen oder einfacher Download (z.B. bei .mp3 files); PDFs hingegen öffneten automatisch in einem Fenster und wurden dargestellt. Nervig wurde es, sobald die Aktion mithilfe einer DesktopVersion von Apple ausgeführt werden musste. Ich spreche vom Browser Safari, welcher die Dateitypen immer automatisch herunterlädt. Oder ist das eine zentrale Einstellung? Stelle man sich vor, ein falsches Dokument (oder Datei) würde demzufolge heruntergeladen werden. Um auf den eigentlichen Stellenwert hinzudenken: Anzeigen macht durchaus Sinn, wenn die Datei gesehen werde möchte, bevor sie auf der eigenen Festplatte oder im eigenen media storage landet. Man könnte es als Pluspunkt anerkennen.

**Comment by ptitmouton** [comment]
Man kann es wie gesagt leicht steuern zB mit Content-Disposition oder dem [download-Attribut](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#download), ob sich der Browser dran hält ist eine andere Frage. iOS hatte ja nun ganz lange keine Dateiverwaltung, da konnte man mit Downloads nicht sehr viel anfangen.

Unabhängig davon bin ich der Meinung dass ein *Download*-Modul auch *downloaden* sollte.
