### ISSUE TITLE
[Bug]: Nachrichtensystem: Benachrichtigung über neue Nachricht wird bei einer ausgehenden Nachricht mehrfach versandt

### ISSUE THREAD

**Issue by techotline** [lotta-schule/core#25]
### Bug-Beschreibung

Hängt das mit der App zusammen?

<img width="416" alt="Bildschirmfoto 2024-03-16 um 13 22 53" src="https://github.com/lotta-schule/ios/assets/153733311/4f199007-59b8-40f5-9abc-427d436b8b18">

### Gerätekategorie

Trifft hier nicht zu

**Comment by ptitmouton** [comment]
Ja das ist wirklich unglaublich nervig. Hab etwa 30 Push-Nachrichten bekommen bevor ich dann den Server zum Neustart gezwungen habe ...
Saß auch gerade am Rechner und hab gleich mal in dei Logs geschaut. Das Problem scheint zu sein dass der Push-Nachrichten-Service etwas überfordert ist und die Anfrage nicht schnell genug beantworten kann, so dass der Absinthe Trigger denkt er ist abgestürzt und nochmal triggert (und damit den Push-Nachrichten-Service auch noch weiter unter Last stellt.). Das geht dann so lange bis es zufälligerweise doch klappt.

Die Lösung ist die Anfragen an den PushNotification Service einfach asynchron durchzuführen.

**Comment by ptitmouton** [comment]
Ok es war doch keine ganz so leichte Geburt aber ich denke ich habe eine Lösung gefunden.

Es sind faktisch zwei verschiedene Änderungen, sowohl auf Staging als auch als hotfix 4.1.15 auf prod deployed.

Ich schließe das Ticket erstmal. Ich würde sagen wir beobachten das mal hoffnungsvoll und sollte es aber in den nächsten Tagen doch wieder zu mehrfachen Benachrichtigungen kommen können wir das Ticket wieder öffnen und weitersehen.
